Tokwasp/LEMS-Project

src/main/java/lems/cowshed/config/jwt/JwtFilter.java
src/main/java/lems/cowshed/config/jwt/SecurityConfig.java
src/main/java/lems/cowshed/domain/user/User.java
src/main/java/lems/cowshed/service/CustomUserDetails.java

##
[Comment] : 로그인 설정 주석 추가
##
1. SecurityConfig 주석 추가 했습니다.
2. JwtFilter, UserDetails 주석 추가 했습니다.

docs : 로그인 설정 주석 추가

---

src/main/java/lems/cowshed/api/advice/GeneralAdvice.java
src/main/java/lems/cowshed/api/controller/ErrorResponse.java
src/main/java/lems/cowshed/api/controller/Response.java
src/main/java/lems/cowshed/api/controller/dto/user/response/UserEventResponseDto.java
src/main/java/lems/cowshed/api/controller/dto/user/response/UserMyPageResponseDto.java
src/main/java/lems/cowshed/api/controller/user/UserApiController.java
src/main/java/lems/cowshed/api/controller/user/UserSpecification.java
src/main/java/lems/cowshed/domain/bookmark/Bookmark.java
src/main/java/lems/cowshed/domain/user/User.java
src/main/java/lems/cowshed/domain/user/query/UserEventMyPageQueryDto.java
src/main/java/lems/cowshed/domain/user/query/UserMyPageQueryDto.java
src/main/java/lems/cowshed/domain/user/query/UserQueryRepository.java
src/main/java/lems/cowshed/domain/userevent/UserEvent.java
src/main/java/lems/cowshed/service/UserService.java
src/test/java/lems/cowshed/api/controller/user/UserApiControllerTest.java
src/test/java/lems/cowshed/domain/BaseEntityTest.java
src/test/java/lems/cowshed/domain/bookmark/BookmarkRepositoryTest.java
src/test/java/lems/cowshed/domain/user/query/UserQueryRepositoryTest.java
src/test/java/lems/cowshed/service/BookmarkServiceTest.java
src/test/java/lems/cowshed/service/UserServiceTest.java

##
- 문제 : 반환 헤더 값이 표기 되지 않는 문제
- 방법 : @RestponseStatus / ResponseEntity
@RestponseStatus : 스웨거에 표기 되는 문제 -> 제외 ( 스웨거 커스텀으로 표기중 )
- 해결 : ResponseEntity : 반환 헤더값 + body 내용 반환을 통해 해결 
<pre>
return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponse);
</pre>
##
- 모임 참여 회원 : 회원ID 값을 통해 모임에 참여한 회원 정보 조회
<pre>
public List<UserEventQueryDto> findUserEvent(Long userId) {
return queryFactory
.select(new QUserEventQueryDto(
user.username,
user.gender,
user.mbti,
user.birth,
user.location
))
.from(user)
.join(user.userEvents, userEvent)
.join(userEvent.event, event)
.where(user.id.eq(userId))
.fetch();
}
</pre>
- 마이 페이지 조회 : 회원ID 값을 통해 회원 정보, 북마크 폴더, 회원 참여 모임 조회
<pre>
UserMyPageQueryDto userDto = queryFactory
.select(new QUserMyPageQueryDto(
user.username.as("name"),
user.birth, …

GeneralAdvice ResponseEntity 반환 / 회원 참여 모임, 마이페이지 조회 추가

---

src/main/java/lems/cowshed/api/controller/dto/user/response/UserSignUpValidationDto.java
src/main/java/lems/cowshed/api/controller/user/UserApiController.java
src/main/java/lems/cowshed/api/controller/user/UserSpecification.java
src/main/java/lems/cowshed/config/jwt/SecurityConfig.java
src/main/java/lems/cowshed/config/swagger/SwaggerConfig.java
src/main/java/lems/cowshed/service/UserService.java

##
[ 회원 가입 검증 로직 추가 ]
- 회원 가입시 이메일, 닉네임이 이미 존재 하는지 체크 합니다.
- 미리 체크함으로써 사용자의 불편이 감소 합니다.

회원 가입 이메일/닉네임 검증 추가

---

src/main/java/lems/cowshed/api/controller/dto/user/request/UserSaveRequestDto.java
src/main/java/lems/cowshed/config/jwt/SecurityConfig.java
src/main/java/lems/cowshed/config/swagger/SwaggerConfig.java
src/main/java/lems/cowshed/domain/user/Gender.java

refactor: change gender expression And SecurityConfig

---

src/main/java/lems/cowshed/config/jwt/LoginFilter.java

회원가입 header contentType 제거

---

src/main/java/lems/cowshed/api/controller/dto/event/request/EventSaveRequestDto.java
src/main/java/lems/cowshed/api/controller/dto/event/request/EventUpdateRequestDto.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventDetailResponseDto.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventPreviewResponseDto.java
src/main/java/lems/cowshed/domain/event/Event.java
src/main/java/lems/cowshed/domain/user/query/UserEventMyPageQueryDto.java
src/test/java/lems/cowshed/api/controller/event/EventControllerTest.java

##
[ 모임 날짜 타입 변경 ]
- LocalDateTime To LocalDate

모임 날짜 타입 수정

---

src/main/java/lems/cowshed/api/controller/dto/bookmark/response/BookmarkResponseDto.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventDetailResponseDto.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventPreviewResponseDto.java
src/main/java/lems/cowshed/domain/bookmark/BookmarkStatus.java
src/main/java/lems/cowshed/domain/event/Event.java
src/main/java/lems/cowshed/domain/userevent/UserEvent.java
src/main/java/lems/cowshed/domain/userevent/UserEventRepository.java
src/main/java/lems/cowshed/service/EventService.java
src/test/java/lems/cowshed/domain/bookmark/BookmarkRepositoryTest.java
src/test/java/lems/cowshed/domain/user/query/UserQueryRepositoryTest.java
src/test/java/lems/cowshed/service/EventServiceTest.java

refactor: event apply applicantsCount

---

src/main/java/lems/cowshed/config/jwt/LoginFilter.java

refactor: jwt expiredMs

---

src/main/java/lems/cowshed/api/controller/dto/bookmark/response/BookmarkResponseDto.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventPagingResponse.java
src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/event/EventSpecification.java
src/main/java/lems/cowshed/service/EventService.java
src/test/java/lems/cowshed/service/EventServiceTest.java

refactor: response slice to Dto

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventPreviewResponseDto.java
src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/domain/user/query/UserEventMyPageQueryDto.java
src/main/java/lems/cowshed/domain/user/query/UserQueryRepository.java
src/main/java/lems/cowshed/service/UserService.java
src/test/java/lems/cowshed/api/controller/bookmark/BookmarkApiControllerTest.java
src/test/java/lems/cowshed/domain/bookmark/BookmarkRepositoryTest.java
src/test/java/lems/cowshed/domain/user/query/UserQueryRepositoryTest.java
src/test/java/lems/cowshed/service/UserServiceTest.java

회원 마이 페이지 조회 쿼리 / 반환값 수정

---

src/main/java/lems/cowshed/api/controller/dto/EnumValidator.java
src/main/java/lems/cowshed/api/controller/dto/event/request/EventSaveRequestDto.java

##
- 모임 저장 Enum Validator 적용
- 로그 확인을 위한 Slf4j 제거

Enum parse Error 추가 적용

---

src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/event/EventSpecification.java
src/main/java/lems/cowshed/domain/userevent/UserEvent.java
src/main/java/lems/cowshed/domain/userevent/UserEventRepository.java
src/main/java/lems/cowshed/exception/Message.java
src/main/java/lems/cowshed/exception/Reason.java
src/main/java/lems/cowshed/service/EventService.java
src/test/java/lems/cowshed/service/EventServiceTest.java

모임 참석 해제 추가

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventDetailResponseDto.java
src/main/java/lems/cowshed/domain/event/Event.java
src/test/java/lems/cowshed/api/controller/user/UserApiControllerTest.java

##
[ 모임 상태 Address 제거 ]
- Location으로 모임의 장소를 표기 하기 때문에 중복된 Address 제거

모임 Address 제거

---

src/main/java/lems/cowshed/api/controller/user/UserApiController.java
src/main/java/lems/cowshed/service/UserService.java
src/test/java/lems/cowshed/domain/BaseEntityTest.java
src/test/java/lems/cowshed/service/UserServiceTest.java

##
[ 마이페이지 회원 변경시 닉네임 체크 ]
- 만약 기존의 닉네임과 같다면 닉네임 중복 체크 하지 않는다.

마이 페이지 회원 변경시 닉네임 체크 추가

---

src/main/java/lems/cowshed/domain/event/query/EventQueryRepository.java
src/main/java/lems/cowshed/domain/event/query/MyPageBookmarkedEventQueryDto.java
src/main/java/lems/cowshed/domain/event/query/MyPageParticipatingEventQueryDto.java
src/main/java/lems/cowshed/domain/user/query/MyPageUserQueryDto.java
src/main/java/lems/cowshed/domain/user/query/UserQueryRepository.java

##
[ 마이페이지 필드 변경 ]
- 회원 : 성별 추가
- 모임 : 최대 인원수 추가

마이페이지 조회 회원 성별 / 모임 최대 인원수 추가

---

src/test/java/lems/cowshed/domain/event/query/EventQueryRepositoryTest.java

refactor : EventQueryRepositoryTest add ActiveProfile

---

src/main/java/lems/cowshed/domain/user/query/MyPageUserQueryDto.java
src/main/java/lems/cowshed/domain/user/query/UserQueryRepository.java

마이페이지 회원 정보 지역명 / 소개 추가

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventSimpleInfo.java
src/main/java/lems/cowshed/domain/event/Availability.java
src/main/java/lems/cowshed/domain/event/query/BookmarkedEventSimpleInfoQuery.java
src/main/java/lems/cowshed/domain/event/query/EventQueryRepository.java
src/main/java/lems/cowshed/domain/event/query/ParticipatingEventSimpleInfoQuery.java
src/main/java/lems/cowshed/service/EventService.java
src/main/java/lems/cowshed/service/UserService.java
src/test/java/lems/cowshed/domain/event/query/EventQueryRepositoryTest.java
src/test/java/lems/cowshed/service/EventServiceTest.java
src/test/java/lems/cowshed/service/UserServiceTest.java

##
[ 요구 사항 구현 ]
- 모임 / 북마크한 모임 / 참여한 모임 페이징의 결과를 일치 시켜 주세요.
- 모임 페이징 조회 결과 기준으로 통일
##
[ 모임 Enum Availability 제거 ]
- 참조 되지 않는 Enum 타입 제거

모임 / 북마크한 모임 / 참여한 모임 페이징 조회 스펙 일치

---

src/main/java/lems/cowshed/domain/event/query/BookmarkedEventSimpleInfoQuery.java

##
[ 북마크한 모임 스펙 변경 ]
- status To bookmarkStatus

refactor: Match the event paging api specs

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventSimpleInfo.java
src/main/java/lems/cowshed/domain/event/query/BookmarkedEventSimpleInfoQuery.java
src/main/java/lems/cowshed/domain/event/query/ParticipatingEventSimpleInfoQuery.java

##
[ 요구사항 ]
- 페이징 반환타입을 LocalDateTime으로 바꿔주세요.

모임 / 참여 모임 / 북마크한 모임 조회 반환값 수정

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventSimpleInfo.java

##
[ 모임 조회 수정 ]
- getter로 인한 eventId 중복 반환 제거

refactor : 모임 조회 식별자 Ignore

---

src/main/java/lems/cowshed/api/controller/user/UserVerificationController.java

##
[ 검증 컨트롤러 URL 수정 ]
- /user -> /users

refactor: 회원 검증 컨트롤러 URL 수정

---

src/main/java/lems/cowshed/config/jwt/SecurityConfig.java
src/main/java/lems/cowshed/config/swagger/SwaggerConfig.java

##
[ swagger / security 검증 컨트롤러 URL 추가 및 토큰 제거 ]

refactor: 스웨거 / 시큐리티 검증 컨트롤러 수정

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventInfo.java
src/main/java/lems/cowshed/domain/bookmark/BookmarkStatus.java
src/main/java/lems/cowshed/domain/event/Event.java
src/main/java/lems/cowshed/domain/event/query/EventQueryRepository.java
src/main/java/lems/cowshed/domain/userevent/UserEvent.java
src/main/java/lems/cowshed/service/EventService.java
src/test/java/lems/cowshed/service/EventServiceTest.java

- Dto 조회시 한번에 모든필드 조회 불가
- Dto 조회 함수 가독성이 좋지 않음
##
##
##
##

refactor: 모임 조회 Dto -> entity 변경

---

src/main/java/lems/cowshed/api/controller/dto/recurring/event/RecurringEventSaveRequest.java
src/main/java/lems/cowshed/api/controller/recurring/event/RecurringEventController.java
src/main/java/lems/cowshed/api/controller/recurring/event/RecurringEventSpecification.java
src/main/java/lems/cowshed/domain/recurring/event/RecurringEvent.java
src/main/java/lems/cowshed/domain/recurring/event/RecurringEventRepository.java
src/main/java/lems/cowshed/service/RecurringEventService.java
src/test/java/lems/cowshed/api/controller/recurring/event/RecurringEventControllerTest.java
src/test/java/lems/cowshed/service/RecurringEventServiceTest.java

feature: 정기 모임 등록 추가

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventInfo.java
src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/event/EventSpecification.java
src/main/java/lems/cowshed/domain/UploadFile.java
src/main/java/lems/cowshed/service/event/EventService.java
src/test/java/lems/cowshed/api/controller/event/EventControllerTest.java
src/test/java/lems/cowshed/service/event/EventServiceTest.java

feature: 모임 조회 반환값 변경

---

src/main/java/lems/cowshed/api/controller/dto/event/response/EventInfo.java
src/main/java/lems/cowshed/api/controller/dto/event/response/EventWithRegularInfo.java
src/main/java/lems/cowshed/api/controller/dto/regular/event/RegularEventInfo.java
src/main/java/lems/cowshed/api/controller/dto/regular/event/RegularEventSaveRequest.java
src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/event/EventSpecification.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventController.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventSpecification.java
src/main/java/lems/cowshed/domain/event/Event.java
src/main/java/lems/cowshed/domain/event/participation/EventParticipantRepository.java
src/main/java/lems/cowshed/domain/event/participation/EventParticipation.java
src/main/java/lems/cowshed/domain/event/participation/Participants.java
src/main/java/lems/cowshed/domain/event/query/EventQueryRepository.java
src/main/java/lems/cowshed/domain/regular/event/RegularEvent.java
src/main/java/lems/cowshed/domain/regular/event/RegularEventRepository.java
src/main/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipation.java
src/main/java/lems/cowshed/domain/user/query/UserQueryRepository.java
src/main/java/lems/cowshed/exception/Reason.java
src/main/java/lems/cowshed/service/RegularEventService.java
src/main/java/lems/cowshed/service/event/EventParticipationService.java
src/main/java/lems/cowshed/service/event/EventService.java
src/test/java/lems/cowshed/api/controller/event/EventControllerTest.java
src/test/java/lems/cowshed/api/controller/recurring/event/RegularEventControllerTest.java
src/test/java/lems/cowshed/domain/event/query/EventQueryRepositoryTest.java
src/test/java/lems/cowshed/domain/user/query/UserQueryRepositoryTest.java
src/test/java/lems/cowshed/service/RegularEventServiceTest.java
src/test/java/lems/cowshed/service/event/EventParticipationServiceTest.java
src/test/java/lems/cowshed/service/event/EventServiceTest.java
src/test/java/lems/cowshed/service/user/UserServiceTest.java

##
- LocalDate To LocalDateTime
---
- EventParticipant To EventParticipation
---
- 모임: 기본 정보 + 참여 인원 수(O) + 제작자 여부(O) + 참여 여부(O) + 북마크 여부(O)
- 정기 모임 : 기본 정보 + 참여 인원 수(O) + 참여 여부(O)
- 테스트 여부 O 체크

feature: 모임 / 정기 모임 상세 조회 추가

---

src/main/java/lems/cowshed/api/controller/dto/event/request/EventUpdateRequestDto.java
src/main/java/lems/cowshed/api/controller/dto/regular/event/request/RegularEventEditRequest.java
src/main/java/lems/cowshed/api/controller/dto/regular/event/response/RegularEventSimpleInfo.java
src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/event/EventSpecification.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventController.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventSpecification.java
src/main/java/lems/cowshed/domain/event/Event.java
src/main/java/lems/cowshed/domain/event/EventEditCommand.java
src/main/java/lems/cowshed/domain/regular/event/RegularEvent.java
src/main/java/lems/cowshed/domain/regular/event/RegularEventEditCommand.java
src/main/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipation.java
src/main/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipationRepository.java
src/main/java/lems/cowshed/exception/Message.java
src/main/java/lems/cowshed/service/RegularEventService.java
src/main/java/lems/cowshed/service/event/EventService.java
src/test/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipationRepositoryTest.java
src/test/java/lems/cowshed/service/RegularEventServiceTest.java
src/test/java/lems/cowshed/service/event/EventServiceTest.java

##
- 모임 참여 회원 수 > 변경 최대 인원 예외 발생
- ex) 모임 참가 인원 : 10명 / 변경 최대 인원 : 5명 
- 테스트 여부 : 모임 ( O ), 정기 모임 ( X )
---
- 모임 생성 회원은 해당 모임에 참여 한다.
- 테스트 여부 : 모임 ( O ), 정기 모임 ( O )
---
- 테스트 여부 : ( O )

feature: 모임 / 정기 모임 수정 및 조회 추가

---

src/main/java/lems/cowshed/api/controller/comment/CommentController.java
src/main/java/lems/cowshed/api/controller/comment/CommentSpecification.java
src/main/java/lems/cowshed/api/controller/dto/comment/response/CommentInfo.java
src/main/java/lems/cowshed/api/controller/dto/comment/response/CommentsInfo.java
src/main/java/lems/cowshed/api/controller/dto/regular/event/response/RegularParticipantsInfo.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventController.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventSpecification.java
src/main/java/lems/cowshed/api/controller/regular/event/participation/RegularEventParticipationController.java
src/main/java/lems/cowshed/domain/comment/Comment.java
src/main/java/lems/cowshed/domain/regular/event/RegularEventRepository.java
src/main/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipation.java
src/main/java/lems/cowshed/domain/regular/event/participation/RegularEventParticipationRepository.java
src/main/java/lems/cowshed/exception/Message.java
src/main/java/lems/cowshed/service/comment/CommentService.java
src/main/java/lems/cowshed/service/regular/event/RegularEventParticipationService.java
src/main/java/lems/cowshed/service/regular/event/RegularEventService.java
src/test/java/lems/cowshed/service/RegularEventServiceTest.java
src/test/java/lems/cowshed/service/comment/CommentServiceTest.java
src/test/java/lems/cowshed/service/regular/event/RegularEventParticipationServiceTest.java

##
- 정기 모임 최대 인원수 추가
---
- 정기 모임 참여시 이미 참여한 정기 모임인지 체크 추가
---
##
- 자신이 등록한 댓글인지 여부 추가
---
- 누락된 정기 모임 삭제 추가

refactor / fix : 오류 수정 및 코드 리팩토링

---

src/main/java/lems/cowshed/api/controller/post/PostController.java
src/main/java/lems/cowshed/api/controller/post/PostSpecification.java
src/main/java/lems/cowshed/dto/regular/event/response/RegularEventPagingInfo.java
src/main/java/lems/cowshed/repository/post/PostRepository.java
src/main/java/lems/cowshed/service/post/PostService.java
src/test/java/lems/cowshed/domain/post/PostRepositoryTest.java
src/test/java/lems/cowshed/service/RegularEventServiceTest.java
src/test/java/lems/cowshed/service/post/PostServiceTest.java

fix : 정기 모임 / 게시글 페이징 조회 수정

---

src/main/java/lems/cowshed/api/controller/post/PostController.java
src/main/java/lems/cowshed/api/controller/post/PostSpecification.java
src/main/java/lems/cowshed/dto/post/response/PostSimpleInfo.java
src/main/java/lems/cowshed/service/post/PostService.java
src/test/java/lems/cowshed/service/post/PostServiceTest.java

feat: 게시글 조회 추가

---

src/test/java/lems/cowshed/service/BookmarkServiceTest.java

##
[ 북마크 테스트 오류 수정 ]
- 북마크 삭제 테스트 오류 수정

fix: 테스트 오류 수정

---

src/main/java/lems/cowshed/api/controller/event/EventController.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventController.java

##
- Get은 Body를 지원 하지 않기 때문에 Post로 변경

fix: 검색 조회 HttpMethod Get To Post

---

src/main/java/lems/cowshed/api/controller/regular/event/RegularEventController.java
src/main/java/lems/cowshed/api/controller/regular/event/RegularEventSpecification.java
src/main/java/lems/cowshed/dto/regular/event/response/RegularEventSearchInfo.java
src/main/java/lems/cowshed/dto/regular/event/response/RegularEventSearchResponse.java
src/main/java/lems/cowshed/repository/event/query/EventQueryRepository.java
src/main/java/lems/cowshed/repository/regular/event/RegularEventQueryRepository.java
src/main/java/lems/cowshed/service/regular/event/RegularEventService.java
src/test/java/lems/cowshed/service/RegularEventServiceTest.java

##
- 회원이 모임 참여한 경우 정기 모임 참여 모달창 표기 
- 회원이 모임 참여하지 않은 경우 모임 상세 창으로 이동

feat: 정기 모임 검색시 회원의 모임 참여 여부 추가

---

src/main/java/lems/cowshed/api/controller/user/UserApiController.java
src/main/java/lems/cowshed/api/controller/user/UserMyPageController.java
src/main/java/lems/cowshed/api/controller/user/UserMyPageSpecification.java
src/main/java/lems/cowshed/dto/user/mypage/MyPageBookmarkedEventsInfo.java
src/main/java/lems/cowshed/dto/user/mypage/MyPageInfo.java
src/main/java/lems/cowshed/dto/user/mypage/MyPageParticipatedEventsInfo.java
src/main/java/lems/cowshed/repository/bookmark/BookmarkRepository.java
src/main/java/lems/cowshed/repository/event/EventRepository.java
src/main/java/lems/cowshed/repository/event/participation/EventParticipantRepository.java
src/main/java/lems/cowshed/repository/user/query/UserMyPageQueryRepository.java
src/main/java/lems/cowshed/service/user/UserMyPageService.java

##
- 회원이 참여한 모임 페이징 조회
- 회원이 북마크한 모임 페이징 조회
##
[ 작업한 피그마 부분 스크린 샷]

feature: [ 마이 페이지 ] 회원이 참여한 모임, 북마크한 모임 페이징 조회 추가
